name: Dev Deployment-test

on:
  push:
    branches:
    - development-test
jobs:
  sanit_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         python devops/install.py
       
      - name: Sanity Setup 
        env:
          PROJECT_NAME: "dev-demo"
          PROJECT_ID: "bre6fb2q"
          DATEAET_NAME: "devdataset"
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          python devops/sanity.py
                   
    # - name: Sanity Check 
    #   run: sudo sanity check
        
     # - name: Sonar Analyis 
     #   run: |
     #     BRANCH=`echo ${GITHUB_REF} | awk -F "/" '{print $NF}'`
     #     echo "sonar.projectName=Nexxus-Linnox-${BRANCH}" >> devops/sonar-project.properties 
     #     echo "sonar.login=${{ secrets.SONAR_AUTH_TOKEN}}" >> devops/sonar-project.properties
     #     echo "sonar.host.url=${{ secrets.SONAR_HOST_URL }}" >> devops/sonar-project.properties
     #     sudo ./sonar/bin/sonar-scanner -Dproject.settings=./devops/sonar-project.properties      
           
    #  - name: Sanity Build 
     #   run: | 
     #     sudo sanity build
          
      - name: Deploy to Sanity
        run: | 
          ls /home/runner/.config/config.json
          cat  /home/runner/.config/config.json
 
                 
     #    sudo mkdir -p /home/runner/.config/sanity/ 
     #    sudo cp -p config.json /home/runner/.config/sanity/
     #    sudo sed -i "s|SANITY_AUTH_TOKEN|`echo ${{ secrets.SANITY_AUTH_TOKEN }}`|g" /home/runner/.config/sanity/config.json
     #    echo `cat sanity.json  | jq -r .project.name` | sudo sanity deploy
     
     # - name: Deploy to Netlify
     #   env:
     #     SITE_ID: "b0a2b151-10a4-4e8f-83fc-d6ef9ce1fffb"
     #   run: |
     #    export  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
     #    sudo netlify deploy -p --auth $NETLIFY_AUTH_TOKEN  -s ${SITE_ID}
