name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v0.0.1
      with:
       host: ${{ secrets.SONAR_HOST_URL }}
       projectBaseDir: src
       login: ${{ secrets.SONAR_AUTH_TOKEN}}
   
