name: CI
on:
  push:
    branches:
    - feature-*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
        sudo tar xzf ZAP_2.9.0_Linux.tar.gz
        cd ZAP_2.9.0
        sudo ls -l
    
