name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli  
       
      #- name: Sanity check 
      #  run: sudo sanity check
        
      #- name: Sanity build 
      #  run: | 
      #   sudo chmod 777 -R ${GITHUB_WORKSPACE}
      #   sudo sanity build
          
      - name: sanity deployment
       # env:
       #   SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          export SANITY_AUTH_TOKEN="540072cccdc9ceeda73809eca352f0ffa8084cd1"
          env | grep SANITY_AUTH_TOKEN
          echo `cat sanity.json  | jq -r .api.projectId` | sudo sanity deploy
       # sudo mkdir -p /home/runner/.config/sanity/ 
       # sudo cp -p config.json /home/runner/.config/sanity/ 
       # cat /home/runner/.config/sanity/config.json
          
       
          
             
 
     
         
   
  
    
