name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    name: sanity build
    runs-on: ubuntu-latest

    steps:
    - name: Install NPM and sanity 
      run: |
        sudo apt update
        sudo apt install nodejs
        sudo npm install -g @sanity/cli
        sudo yes "" | sudo sanity login
        sudo sanity check && sudo  sanity build
   
  
    
