name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli  
       
      #- name: Sanity check 
      #  run: sudo sanity check
        
      #- name: Sanity build 
      #  run: | 
      #   sudo chmod 777 -R ${GITHUB_WORKSPACE}
      #   sudo sanity build
          
      - name: sanity deployment
        run: |
         sudo mkdir -p /home/runner/.config/sanity/ 
         sudo cp -p config.json /home/runner/.config/sanity/
         sudo sed -i "s|SANITY\_AUTH\_TOKEN|$\{\{\ secrets\.GITHUB_TOKEN\ \}\}|g" /home/runner/.config/sanity/config.json
         sudo cat /home/runner/.config/sanity/config.json 
         echo `cat sanity.json  | jq -r .api.projectId` | sudo sanity deploy
       
             
 
     
         
   
  
    
