name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_check:
    name: sanity check 
    runs-on: ubuntu-latest

    steps:
    - name: Install NPM and sanity 
      run: |
        sudo apt update
        sudo apt install nodejs
        sudo npm install -g @sanity/cli
        cd ${WORKSPACE}
        sudo sanity check
    
