name: CI
on:
  push:
    branches:
    - feature-*
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    #- name: Install ZAP
    #  run: |
    #    wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
    #    sudo apt update && sudo apt install nodejs && sudo pip install zapcli
    #    sudo tar xzf ZAP_2.9.0_Linux.tar.gz && cd ZAP_2.9.0
    #    ./zap.sh -daemon  -config api.disablekey=true & 
    #    sleep 30
    #    sudo /usr/local/bin/zap-cli -p 8080 open-url https://dev-demo.netlify.com \
    #    && /usr/local/bin/zap-cli -v -p 8080 spider  https://dev-demo.netlify.com \
    #    && /usr/local/bin/zap-cli -v -p 8080 active-scan  --recursive https://dev-demo.netlify.com \
    #    && sudo mkdir -p ${GITHUB_WORKSPACE}/zapreport && sudo chmod 777 ${GITHUB_WORKSPACE}/zapreport \
    #    && /usr/local/bin/zap-cli -p 8080  report  -o ${GITHUB_WORKSPACE}/zapreport/index.html -f html 
    #- name: Export s3 values 
    #  run: |
    #    export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
    #    && export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
    ##    && aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} \
     #   && aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} \
   #     && sed -i s"|ZAP\ Scanning\ Report|Nexxus\ ZAP\ Report\ $(date +%d-%m-%Y-%T)|g" ${GITHUB_WORKSPACE}/zapreport/index.html \
    #    && aws s3 sync ${GITHUB_WORKSPACE}/zapreport/ s3://zaptestscan --acl public-read \
    #    && echo " " && echo "Please check the report at https://zaptestscan.s3.amazonaws.com/index.html"
        
    - name: Tag the Code
      run: |
         VERSION=`cat ${GITHUB_WORKSPACE}/package.json | jq -r .version
         echo $VERSION
        
    
