name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: sonar-scanner
      uses: Warchant/setup-sonar-scanner@v1
    - name: sonar scanner
      run: |
        BRANCH=`echo ${GITHUB_REF} | awk -F "/" '{print $NF}'`
        echo "sonar.projectName=Nexxus-Linnox-${BRANCH}" >> devops/sonar-project.properties 
        echo "sonar.login=${{ secrets.SONAR_AUTH_TOKEN}}" >> devops/sonar-project.properties
        echo "sonar.host.url=${{ secrets.SONAR_HOST_URL }}" >> devops/sonar-project.properties
        sudo sonar-scanner -Dproject.settings=./devops/sonar-project.properties 
        
      
