name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
     # - name: Install Packages 
     #   run: |
      #   sudo apt update
     #    sudo apt install nodejs
       #  sudo npm install -g @sanity/cli  
       
     # - name: Sanity check 
      #  run: sudo sanity check
        
     # - name: Sanity build 
     #   run: | 
     #    sudo chmod 777 -R ${GITHUB_WORKSPACE}
      #   sudo sanity build
          
      - name: sanity login and deployment
        env:
          SANITY_AUTH_TOKEN: ${{ SANITY_AUTH_TOKEN }}
        run: |
         # echo -e  "\U+02C5" | sudo sanity login 
          #echo `cat sanity.json  | jq -r .api.projectId` | sudo sanity deploy
         env 
             
 
     
         
   
  
    
