name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.9.1
      - name: Test all 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli
         echo $PWD
         echo "====="
         echo $GITHUB_WORKSPACE
         echo "====="
         echo $WORKSPACE
   
  
    
