name: CI
on:
  push:
    branches:
    - feature-*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ZAP
      run: |
        wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
        apk add nodejs
        npm install -g zap-cli
        sudo tar xzf ZAP_2.9.0_Linux.tar.gz && cd ZAP_2.9.0
        ./zap.sh -daemon &
        /usr/local/bin/zap-cli -p 8080 open-url https://dev-demo.netlify.com/
    
