name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli   
         
      - name: Sanity check 
        run: sudo sanity check
        
      - name: Sanity build 
        run: | 
          sudo chmod 777 -R ${GITHUB_WORKSPACE}
          sudo sanity build
      - name: check dist folder
        run: ls -l  
      
      - name: sanity login and deployment
        run: |
           echo -e  "\U+02C5" | sudo sanity login > login.txt
           URL=`cat login.txt |  cut -d":" -f2`
           curl -L -u"a7fcbd595fe92c92e1a90358b4f221ebb5482555" https:\$URL
           sudo sanity deploy
     
   
     
         
   
  
    
