name: CI
on:
  push:
    branches:
    - feature-*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v1
    - name: Install ZAP
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        pwd
        cat ~/.aws/credentials
        aws s3 ls
     #   wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
     #   sudo apt update && sudo apt install nodejs && sudo pip install zapcli
     #   sudo tar xzf ZAP_2.9.0_Linux.tar.gz && cd ZAP_2.9.0
     #   ./zap.sh -daemon  -config api.disablekey=true & 
     #   sleep 30
     ##   sudo /usr/local/bin/zap-cli -p 8080 open-url https://dev-demo.netlify.com \
     #   && /usr/local/bin/zap-cli -v -p 8080 spider  https://dev-demo.netlify.com \
     #   && /usr/local/bin/zap-cli -v -p 8080 active-scan  --recursive https://dev-demo.netlify.com \
     #   && /usr/local/bin/zap-cli -p 8080  report  -o /tmp/index.html -f html 
          
        
        
        
    
