name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli   
         
      - name: Sanity check 
        run: sudo sanity check
        
      - name: Sanity build 
        run: 
          sudo chmod 777 -R ${GITHUB_WORKSPACE}
          sudo sanity build
      - name: check dist folder
        run: ls -l  
      
      - name: sanity login
        run: yes ""| sudo sanity login
      - name: Sanity deploy
        run: sudo sanity deploy
     
     
         
   
  
    
