name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Packages 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo apt install jq firefox
         sudo npm install -g @sanity/cli   
         
      #- name: Sanity check 
      #  run: sudo sanity check
        
      #- name: Sanity build 
      #  run: | 
       #   sudo chmod 777 -R ${GITHUB_WORKSPACE}
       #   sudo sanity build
      #- name: check dist folder
      #  run: ls -l  
      
      - name: sanity login and deployment
        run: |
           ifconfig 
           export DISPLAY=127.0.0.1:0
           firefox 
           #echo -e  "\U+02C5" | sudo sanity login > login.txt
           #cat login.txt | sed "s|Please\ open\ a\ browser\ at\ ||g"
           #sudo firefox `cat login.txt | sed "s|Please\ open\ a\ browser\ at\ ||g"`
           #echo `cat sanity.json  | jq -r .api.projectId` | sudo sanity deploy 
     
   
     
         
   
  
    
