name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Test all 
        run: |
         sudo apt update
         sudo apt install nodejs
         sudo npm install -g @sanity/cli
         echo $PWD
         sudo ls -l
         echo $GITHUB_WORKSPACE
         echo "====="
         
   
  
    
