name: Sanity_CICD

on:
  push:
    branches:
    - master
jobs:
  sanit_build:
    runs-on: ubuntu-18.04
    steps:
      #- uses: actions/checkout@v2.0.0
     # - name: Install Packages 
     #   run: |
      #   sudo apt update
      #   sudo apt install nodejs
      #   sudo npm install -g @sanity/cli  
       
      #- name: Sanity check 
      #  run: sudo sanity check
        
      #- name: Sanity build 
      #  run: | 
      #   sudo chmod 777 -R ${GITHUB_WORKSPACE}
      #   sudo sanity build
          
      - name: sanity deployment
       # env:
       #   SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          echo ${{ secrets.SANITY_AUTH_TOKEN }}
          env | grep SANITY_AUTH_TOKEN
       # export SANITY_AUTH_TOKEN=skAzK1TJJd7BZ7nHFsVVCBZ2DzbjNQ5Zwc3I3R59ZJDPinXQe6ziby3rH4iVFAIy56EPZh3L7dRp25XMa
       # echo `cat sanity.json  | jq -r .api.projectId` | sudo sanity deploy
       # sudo mkdir -p /home/runner/.config/sanity/ 
       # sudo cp -p config.json /home/runner/.config/sanity/ 
       # cat /home/runner/.config/sanity/config.json
          
       
          
             
 
     
         
   
  
    
